version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  test-ejecutar-redis:
    docker:
      - image: redis:4.0.9
    steps:
      - checkout
      - run:
          name: Ejecutando Redis

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
