version: 2.1

orbs:
  maven: circleci/maven@0.0.12

dependencies:
  pre:
    - gem install bundler --pre
    - wget http://download.redis.io/releases/redis-3.2.0.tar.gz
    - tar xzf redis-3.2.0.tar.gz
    - cd redis-3.2.0 && make
  cache_directories:
    - redis-3.2.0

workflows:
  maven_test:
    jobs:
      - sudo service redis-server --port 6391 start
      - maven/test # checkout, build, test, and upload test results