version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
services:
    redis:
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        ports:
            - "6379:6379"

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results