version: "3.7"

orbs:
  maven: circleci/maven@0.0.12

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
    
volumes:
  redis-data:

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results