version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  test-ejecutar-redis:
    docker:
      - image: redis:3.2
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for Redis to receive connections
          command: dockerize -wait tcp://localhost:6379 -timeout 1m

workflows:
  maven_test:
    jobs:
      - test-ejecutar-redis
      - maven/test # checkout, build, test, and upload test results