version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  test-ejecutar-redis:
    docker:
      - image: redis
    steps:
      - run:
          name: Wait for Redis to receive connections
          command: dockerize -wait tcp://0.0.0.0:6379 -timeout 1m

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
