version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  test-ejecutar-redis:
    docker:
      - image: redis:3.2
    steps:
      - checkout

workflows:
  maven_test:
    jobs:
      - test-ejecutar-redis
      - maven/test # checkout, build, test, and upload test results