version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  build:
    docker:
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673


workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
