version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      - image: redis:2.8.19
    working_directory: /project
    steps:
      - run: |
          apt-get update && apt-get install -y redis-tools
          echo "CONFIG SET save ''" | redis-cli -x

workflows:
  maven_test:
    jobs:
      - test-ejecutar-redis
      - maven/test # checkout, build, test, and upload test results