version: 2.1
  
jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: /project
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: 
          name: install dependencies and exec tests
          command: |
            echo "hola mundo"
            docker-compose run javaclient mvn install

workflows:
  maven_test:
    jobs:
      - build_and_test