version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  test-ejecutar-redis:
    docker:
      - image: redis:3.2
    steps:
      - checkout
      - run:
            name: Install wget
            command: sudo apt-get install wget
      - run:
            name: Dockerize v0.6.0
            command: wget [removedhttp-new-user]jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz
      - run:
            name: Wait for Redis
            command: dockerize -wait [removed-link]localhost:6379 -timeout 2m

workflows:
  maven_test:
    jobs:
      - test-ejecutar-redis
      - maven/test # checkout, build, test, and upload test results