version: 2.1
  
jobs:
  build_and_test:
    docker:
      - image: mouserd/java-redis:v2
    working_directory: /project
    steps:
      - run: 
          name: install dependencies
          command: |
            echo "hola mundo"
            chmod u+x mvnw
            ./mvnw install -Dmaven.test.skip=true
      - run: 
          name: testing
          command: |
            ./mvnw test


workflows:
  maven_test:
    jobs:
      - build_and_test